CELEB_IDENTITY_PATH = "../Anno/identity_CelebA.txt"
CELEB_IMAGES_ALIGN_PATH = "../img_align_celeba"

CELEB_TRAINING_PATH = "../final_features/imgs"
TRAIN_FEATURES_CSV_PATH = "../final_features/train_features.csv"
TEST_FEATURES_CSV_PATH = "../final_features/test_features.csv"
MODEL_SAVE_PATH = "../saved_models/"

IMAGE_SIZE = float(256.0)
RANDOM_SEED = 47
TEST_SIZE = 0.2
PATCH_SIZE = 32 
N = (IMAGE_SIZE / PATCH_SIZE) *  (IMAGE_SIZE / PATCH_SIZE)

ATTENTION_HEADS = 16
EMBEDDING_DIM = 1024
CHANNELS = 3

SCALE = 3
L = 12
CLASSES = 306

BATCH_SIZE = 256 # VARIABLE TO CHANGE
CNN_EMBEDDING = 512
CHUNK_SIZE = 16

INITIAL_T= 1000
T_MULT= 1
S = 64

M = 0.50